---
apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project={{ .Values.serviceName }}&var-version={{ .Values.imageTag }}
      labels:
        app: {{ .Values.serviceName }}
        version: "{{ .Values.imageTag }}"
        date: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      {{- if (.Values.acrSecretName) }} 
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
      containers:
      - env:
        - name: AUTHORISATION_REALM_NAME
          value: {{ .Values.authorisationRealmName }}
        - name: AUTHORISATION_SERVER_HOST_AND_PORT
          value: {{ .Values.authorisationServerHostAndPort }}
        {{- if (.Values.authorisationExternalRealmURL) }} 
        - name: EXTERNAL_REALM_URL
          value: {{ .Values.authorisationExternalRealmURL }}          
        {{- end }}
        {{- if (.Values.hapiSocketTimeoutInSecs) }} 
        - name: HAPI_SOCKET_TIMEOUT_IN_SECS
          value: {{ .Values.hapiSocketTimeoutInSecs }}
        {{- end }}
        {{- if (.Values.dnsEntry) }} 
        - name: DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_DNS_ENTRY
          value: {{ .Values.dnsEntry }}
        {{- end }}
        {{- if (.Values.externalDnsEntry) }} 
        - name: EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_EXTERNAL_DNS_ENTRY
          value: {{ .Values.externalDnsEntry }}
        {{- end }}
        {{- if (.Values.authSvcIP) }} 
        - name: AUTH_SVC_IP
          value: {{ .Values.authSvcIP }}          
        {{- end }}
        {{- if (.Values.ladonSvcIP) }} 
        - name: LADON_SVC_IP
          value: {{ .Values.ladonSvcIP }}          
        {{- end }}
        {{- if (.Values.wildflyAdminUser) }} 
        - name: WILDFLY_MANAGEMENT_USER
          value: {{ .Values.wildflyAdminUser }}
        # TODO this should be a secret, or potentially no management user at all
        - name: WILDFLY_MANAGEMENT_PASSWORD
          value: {{ .Values.wildflyAdminPwd }}
        {{- end }}
        - name: WILDFLY_LOG_LEVEL
          value: "{{ .Values.wildflyLogLevel | default "WARN" }}"
        - name: JAVAX_NET_DEBUG
          value: "{{ .Values.javaxNetDebug | default "none" }}"
        - name: WILDFLY_ENABLE_DEBUG
          value: "{{ .Values.wildflyEnableDebug | default "no" }}"
        - name: KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: DEPLOYMENT_FILE_NAME
          value: {{ .Values.deploymentFileName }}
        - name: SYSTEM_ADMIN_FAILURE_NOTIFICATION_EMAIL
          value: {{ .Values.systemAdminFailureNotificationEmail }}
        - name: FAILURE_NOTIFICATION_SENDER_EMAIL
          value: {{ .Values.failureNotificationSenderEmail }}
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_BASE_PORT_INSIDE_POD
          value: "{{ .Values.basePortInsidePod | default .Values.basePort }}"
        - name: {{ upper .Values.serviceName | replace "-" "_" }}_{{ upper .Release.Namespace | replace "-" "_" }}_BASE_PORT
          value: "{{ .Values.basePort }}"
        - name: HELM_RELEASE_TIME
          value: "{{ date "20060102-150405" .Release.Time }}"
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: JVM_MAX_HEAP_SIZE
          value: "{{ .Values.jvmMaxHeapSizeMB }}m"
        # Set the minimum memory that will be available on the node to assign to the container to be the jvmMaxHeapSizeMB plus 128 MB 
        # for the native heap and operation system processes associated with running Java
        # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#motivation-for-memory-requests-and-limits
        # and https://www.alibabacloud.com/blog/kubernetes-demystified-restrictions-on-java-application-resources_594108
        resources:
          requests:
            memory: "{{ add 128 .Values.jvmMaxHeapSizeMB }}Mi"
        image: {{ .Values.dockerRepo }}interface-hl7messaging-jgroups:{{ .Values.imageTag }}            
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 5
        name: hl7-messaging-jgroups
        ports:
        - containerPort: 3200
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 5
        securityContext:
          privileged: false     
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}